version: '3'

services:
  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: notifydb
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Elixir application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MIX_ENV: prod
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
